<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/12
 * Time: 14:30
 */

namespace app\admin\controller;


class Article extends Admin
{
    protected $Article;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Article = model('Posts');
        $this->Category = model('Category');
    }

    /**
     * 文章列表
     * @return \think\response\View
     */
    public function index()
    {
        $list = $this->Article->select()->toArray();

        int_to_string($list, array('status' => array(1 => '是', 0 => '否')));


        $this->setMeta('文章列表');
        $this->assign('list', $list);
        return view();
    }


    /**
     * 添加文章
     * @return \think\response\View|void
     */
    public function add()
    {
        if (IS_POST) {
            $data = input('post.');
            unset($data['id']);
            $id = $this->Article->save($data);
            if ($id) {
                return $this->success('新增成功', 'article/index');
            } else {
                return $this->error('新增失败');
            }
        } else {
            $this->assign('info', array());
            $this->setMeta('写文章');
            return view('edit');
        }

    }

    public function edit($id = 0)
    {
        if (IS_POST) {
            $data = input('post.');


            $res = $this->Article->save($data, array('id' => $data['id']));
            if ($res) {
                return $this->success('更新成功', 'article/index');
            } else {
                return $this->error('更新失败');
            }
        } else {
            if (empty($id)) {
                return $this->error('请选择要操作的数据!');
            }

            /* 获取数据 */
            $info  = $this->Article->get($id)->toArray();
            if (!$info) {
                return $this->error('参数错误');
            }
            $this->assign('info', $info);
            $this->setMeta('编辑文章');
            return view('edit');
        }
    }

    /**
     * 文章分类
     * @return \think\response\View
     */
    public function cate()
    {
        $list = $this->Category->select()->toArray();

        int_to_string($list, array('status' => array(1 => '是', 0 => '否')));


        $this->setMeta('分类列表');
        $this->assign('list', $list);
        return view();
    }

    /**
     * 增加分类
     * @return \think\response\View|void
     */
    public function addCate()
    {
        if (IS_POST) {
            $data = input('post.');
            unset($data['id']);
            $id = $this->Category->save($data);
            if ($id) {
                return $this->success('新增成功', 'article/cate');
            } else {
                return $this->error('新增失败');
            }
        } else {
            $this->assign('info', array());
            $this->setMeta('新增分类');
            return view('edit_cate');
        }
    }

    public function editCate($id = 0)
    {
        if (IS_POST) {
            $data = input('post.');


            $res = $this->Category->save($data, array('id' => $data['id']));
            if ($res) {
                return $this->success('更新成功', 'article/cate');
            } else {
                return $this->error('更新失败');
            }
        } else {
            if (empty($id)) {
                return $this->error('请选择要操作的数据!');
            }

            /* 获取数据 */
            $info  = $this->Category->get($id)->toArray();
            if (!$info) {
                return $this->error('参数错误');
            }
            $this->assign('info', $info);
            $this->setMeta('编辑分类');
            return view('edit_cate');
        }
    }



}