<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/5
 * Time: 13:33
 */

namespace app\admin\controller;


use think\Db;

class Menu extends Admin
{

    protected $Menu;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Menu = model('Menu');
    }

    /**
     * 菜单列表
     */
    public function index()
    {
        $list = $this->Menu->select()->toArray();

        int_to_string($list, array('hide' => array(1 => '是', 0 => '否'), 'is_dev' => array(1 => '是', 0 => '否')));

        if (!empty($list)) {
            $tree = new \Tree();
            $list = $tree->toFormatTree($list);
        }

        $this->assign('list', $list);
        return view();
    }

    /**
     * 添加菜单
     * @return mixed|void
     */
    public function add()
    {
        if (IS_POST) {
            $data = input('post.');
            unset($data['id']);
            $id   = $this->Menu->save($data);
            if ($id) {
//                session('admin_menu_list', null);
                return $this->success('新增成功', 'menu/index');
            } else {
                return $this->error('新增失败');
            }
        } else {
            $this->assign('info', array('pid' => input('pid')));
            $menus = $this->Menu->select()->toArray();
            $tree  = new \Tree();
            $menus = $tree->toFormatTree($menus);
            if (!empty($menus)) {
                $menus = array_merge(array(0 => array('id' => 0, 'title_show' => '顶级菜单')), $menus);
            } else {
                $menus = array(0 => array('id' => 0, 'title_show' => '顶级菜单'));
            }

            $this->assign('menus', $menus);
            $this->setMeta('新增菜单');
            return view('edit');
        }
    }

    /**
     * 修改菜单
     * @param int $id
     * @return \think\response\View|void
     */
    public function edit($id = 0)
    {
        if (IS_POST) {
            $data = input('post.');

            $res = $this->Menu->save($data, array('id' => $data['id']));
            if ($res) {
                return $this->success('更新成功', 'menu/index');
            } else {
                return $this->error('更新失败');
            }
        } else {
            if (empty($id)) {
                return $this->error('请选择要操作的数据!');
            }

            /* 获取数据 */
            $info  = $this->Menu->get($id)->toArray();
            if (!$info) {
                return $this->error('参数错误');
            }

            $menus = $this->Menu->select()->toArray();
            $tree  = new \Tree();
            $menus = $tree->toFormatTree($menus);

            $menus = array_merge(array(0 => array('id' => 0, 'title_show' => '顶级菜单')), $menus);
            $this->assign('menus', $menus);
            $this->assign('info', $info);
            $this->setMeta('编辑后台菜单');
            return view('edit');
        }
    }


}