<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/6
 * Time: 18:02
 */

namespace app\admin\controller;


class User extends Admin
{
    protected $User; //用户分组
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->User = model('User');
    }
    /**
     * 用户列表
     */
    public function index()
    {
        $list = $this->User->select()->toArray();
        int_to_string($list, array('status' => array(1 => '激活', 0 => '禁用'), 'sex' => array(0 => '中性', 1 => '男', 2 => '女')));

        $this->assign('list', $list);
        $this->setMeta('系统用户');
        return view('index');

    }

    /**
     * 添加用户
     * @return \think\response\View|void
     */
    public function add()
    {
        if (IS_POST) {
            $data = input('post.');

            unset($data['id']);
            $id = $this->User->save($data);
            if ($id) {
                return $this->success('新增成功', 'User/index');
            } else {
                return $this->error('新增失败');
            }
        } else {

            $this->assign('info', array());
            $this->setMeta('新增用户');
            return view('edit');
        }

    }

    /**
     * 修改角色组信息
     * @param int $id
     * @return \think\response\View|void
     */
    public function edit($id = 0)
    {
        if (IS_POST) {
            $data = input('post.');
            if (empty($data['password'])) {
                unset($data['password']);
            }

            $res = $this->User->save($data, array('id' => $data['id']));
            if ($res) {
                return $this->success('更新成功', 'User/index');
            } else {
                return $this->error('更新失败');
            }
        } else {
            if (empty($id)) {
                return $this->error('请选择要操作的数据!');
            }

            /* 获取数据 */
            $info  = $this->User->get($id)->toArray();
            if (!$info) {
                return $this->error('参数错误');
            }

            $this->assign('info', $info);
            $this->setMeta('编辑用户');
            return view();
        }
    }

}